load(":sun.bzl", "define_sun")
load(":sun_tuivm.bzl", "define_sun_tuivm")
load(":sun_oemvm.bzl", "define_sun_oemvm")
load(":sun_vms.bzl", "define_sun_vms")
load(":sun_allyes.bzl", "define_sun_allyes")
load(":canoe.bzl", "define_canoe")
load(":canoe_tuivm.bzl", "define_canoe_tuivm")
load(":canoe_oemvm.bzl", "define_canoe_oemvm")
load(":canoe_vms.bzl", "define_canoe_vms")
load(":vienna.bzl", "define_vienna")
load(":gen3auto.bzl", "define_gen3auto")
load(":msm_common.bzl", "define_signing_keys")
load("//build:msm_kernel_extensions.bzl", "define_top_level_rules")

def define_msm_platforms():
    define_top_level_rules()
    define_signing_keys()
    define_sun()
    define_sun_tuivm()
    define_sun_oemvm()
    define_sun_vms()
    define_sun_allyes()
    define_canoe()
    define_canoe_tuivm()
    define_canoe_oemvm()
    define_canoe_vms()
    define_vienna()
    define_gen3auto()
